binanceExchange/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'binance'

urlpatterns = [
    path('futures/', views.FuturesView.as_view(), name='home'),
    path('futures/send_order/', views.FuturesSendOrderView.as_view(), name='futures_send_order'),
    path('futures/cancel_order/<str:symbol>/', views.FuturesSendOrderView.cancel_order, name='futures_cancel_order'),
    path('futures/reset_stop_orders/<str:symbol>/', views.FuturesSendOrderView.reset_stop_orders, name='futures_reset_stop_orders'),
    path('futures/stop_order_panel/', views.FuturesSendOrderView.stop_order_panel, name='futures_stop_order_panel'),
    path('futures/close_position/<str:symbol>/', views.FuturesSendOrderView.close_position, name='futures_close_position'),
    path('futures/test/', views.FuturesSendOrderView.test, name='futures_test'),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('binanceExchange.urls', 'binance'), namespace='binance')),
    path('', include(('manager.urls', 'manager'), namespace='manager')),
]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.home, name='home'),
]

templates/base.html
<!-- Base template for all binance pages -->
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'base/favicon.ico' %}">
    <title>Daric</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <!-- Icon -->
        <a class="navbar-brand" href="{% url 'manager:home' %}">
            <img src="{% static 'base/favicon.ico' %}" width="30" height="30" class="d-inline-block align-top" alt="Binance">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'manager:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'binance:home' %}">BinanceFutures</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'manager:home' %}">About</a>
                </li>
                <li class="nav-item">
<!-- login or log out -->
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'binance:logout' %}" style="position:absolute ;right: 2%;">Log out</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'binance:login' %}" style="position:absolute ;right: 2%;">Log in</a>
                    {% endif %}
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}" style="position:absolute ;right: 6%;">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'binance:futures_stop_order_panel' %}" style="position:absolute ;right: 9%;">StopOrders</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% block content %} {% endblock %}
            </div>
        </div>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block script %} {% endblock %}
</body>